server:
  port: 8081

spring:
  application:
    name: extranet
  r2dbc:
    url: r2dbc:postgresql://172.23.0.2:5432/sgiextranet?schema=extranet
    username: sgiextranet
    password: sgiextranet
  devtools:
    remote:
      secret: sgi extranet 123

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG